[package]
name = "rustyneedle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = "0.11"
base64 = "0.13.0"
kernel32-sys = "0.2.2"
winapi = { version = "0.3.8", features = [
    "winnt",
    "winuser",
    "errhandlingapi",
    "handleapi",
    "processthreadsapi",
    "securitybaseapi",
]} 

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
strip = true
